### ISSUE TITLE
Not working with "@cucumber/cucumber": "~7.0.0",

### ISSUE THREAD

**Issue by vanozi** [vtimonov/cucumberjs-parallel#12]
In our project we are working with cucumber > 7 
I tried to create a fork but could not make it work.
Would be great if you can have a look at it.

**Comment by arjanassink1978** [comment]
We encounter the same problem. It would be great if you can make it work with cucumber 7

**Comment by vtimonov** [comment]
@vanozi @arjanassink1978 Please, check a new version 2.0.0
